
name: 'enpal_assessment_project'
version: '1.0.0'

profile: 'enpal_assessment_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:     
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt
    search_order:
      - enpal_assessment_project
      - dbt
vars:
  hashing_salt: f24f2fc4-f285-4cab-8eb7-1d50455391d4 # this will be stored in an environment variable
  dbt_project_evaluator:
    models_fanout_threshold: 4 # max number of downstream dependencies for each model
    model_types: ['staging', 'intermediate','marts']
    intermediate_folder_name: "int"
    prep_prefixes: ["int_"]
    marts_prefixes: ["fct_", "dim_", "rep_"]
    exclude_packages: ["elementary"]

models:
  +persist_docs:
    columns: true
  enpal_assessment_project:

    staging:
      +materialized: view  
      +schema: staging

    intermediate:
      +materialized: view      
      +schema: intermediate

    marts:
      +schema: pipedrive_analytics

      dimensions:
        +materialized: table     

      facts:
        +materialized: table 

      reporting:
        +materialized: table  


  elementary:
    +meta:
      owner: "external_package"
    +schema: "enpal_elementary"
    +enabled: true