
name: 'enpal_assessment_project'
version: '1.0.0'

profile: 'enpal_assessment_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:     
  - "target"
  - "dbt_packages"


models:
  +persist_docs:
    columns: true
  enpal_assessment_project:

    staging:
      +materialized: view  
      +schema: staging

    intermediate:
      +materialized: view      
      +schema: intermediate

    marts:
      +schema: pipedrive_analytics

      dimensions:
        +materialized: table     

      facts:
        +materialized: table 

      reporting:
        +materialized: table  


  elementary:
    +meta:
      owner: "external_package"
    +schema: "enpal_elementary"
    +enabled: true